services:
  cpp-devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/idea:cached

    command: /bin/bash -c "while sleep 1000; do :; done"

    cap_add:
      - SYS_PTRACE

    security_opt:
      - seccomp=unconfined